//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_ATM.ServicioAutorizador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTransaccion", Namespace="http://schemas.datacontract.org/2004/07/WCF_Autorizador")]
    [System.SerializableAttribute()]
    public partial class RespuestaTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutorizacion {
            get {
                return this.CodigoAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutorizacionField, value) != true)) {
                    this.CodigoAutorizacionField = value;
                    this.RaisePropertyChanged("CodigoAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((object.ReferenceEquals(this.SaldoField, value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAutorizador.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR1", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR1Response")]
        Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR1(string tarjeta, string cvv, string pin, string vencimiento, string cliente, int idCajero, double monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR1", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR1Response")]
        System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR1Async(string tarjeta, string cvv, string pin, string vencimiento, string cliente, int idCajero, double monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR2", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR2Response")]
        Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR2(string tarjeta, string cvv, string vencimiento, int idCajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR2", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR2Response")]
        System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR2Async(string tarjeta, string cvv, string vencimiento, int idCajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR3", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR3Response")]
        Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR3(string tarjeta, string pinActual, string pinNuevo, string vencimiento, string cvv, int idCajero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WS_AUTORIZADOR3", ReplyAction="http://tempuri.org/IService/WS_AUTORIZADOR3Response")]
        System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR3Async(string tarjeta, string pinActual, string pinNuevo, string vencimiento, string cvv, int idCajero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Prueba_ATM.ServicioAutorizador.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Prueba_ATM.ServicioAutorizador.IService>, Prueba_ATM.ServicioAutorizador.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR1(string tarjeta, string cvv, string pin, string vencimiento, string cliente, int idCajero, double monto) {
            return base.Channel.WS_AUTORIZADOR1(tarjeta, cvv, pin, vencimiento, cliente, idCajero, monto);
        }
        
        public System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR1Async(string tarjeta, string cvv, string pin, string vencimiento, string cliente, int idCajero, double monto) {
            return base.Channel.WS_AUTORIZADOR1Async(tarjeta, cvv, pin, vencimiento, cliente, idCajero, monto);
        }
        
        public Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR2(string tarjeta, string cvv, string vencimiento, int idCajero) {
            return base.Channel.WS_AUTORIZADOR2(tarjeta, cvv, vencimiento, idCajero);
        }
        
        public System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR2Async(string tarjeta, string cvv, string vencimiento, int idCajero) {
            return base.Channel.WS_AUTORIZADOR2Async(tarjeta, cvv, vencimiento, idCajero);
        }
        
        public Prueba_ATM.ServicioAutorizador.RespuestaTransaccion WS_AUTORIZADOR3(string tarjeta, string pinActual, string pinNuevo, string vencimiento, string cvv, int idCajero) {
            return base.Channel.WS_AUTORIZADOR3(tarjeta, pinActual, pinNuevo, vencimiento, cvv, idCajero);
        }
        
        public System.Threading.Tasks.Task<Prueba_ATM.ServicioAutorizador.RespuestaTransaccion> WS_AUTORIZADOR3Async(string tarjeta, string pinActual, string pinNuevo, string vencimiento, string cvv, int idCajero) {
            return base.Channel.WS_AUTORIZADOR3Async(tarjeta, pinActual, pinNuevo, vencimiento, cvv, idCajero);
        }
    }
}
