//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorCliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/ServiciosBancariosWCF")]
    [System.SerializableAttribute()]
    public partial class RespuestaBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioModelo", Namespace="http://schemas.datacontract.org/2004/07/ServiciosBancariosWCF")]
    [System.SerializableAttribute()]
    public partial class UsuarioModelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAutenticacionService")]
    public interface IAutenticacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/AutenticarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/AutenticarUsuarioResponse")]
        SimuladorCliente.ServiceReference1.RespuestaBase AutenticarUsuario(string usuarioEncriptado, string contrasenaEncriptada, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/AutenticarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> AutenticarUsuarioAsync(string usuarioEncriptado, string contrasenaEncriptada, int tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CrearUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/CrearUsuarioResponse")]
        SimuladorCliente.ServiceReference1.RespuestaBase CrearUsuario(SimuladorCliente.ServiceReference1.UsuarioModelo nuevoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CrearUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> CrearUsuarioAsync(SimuladorCliente.ServiceReference1.UsuarioModelo nuevoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarUsuarioResponse")]
        SimuladorCliente.ServiceReference1.RespuestaBase ModificarUsuario(SimuladorCliente.ServiceReference1.UsuarioModelo usuarioModificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> ModificarUsuarioAsync(SimuladorCliente.ServiceReference1.UsuarioModelo usuarioModificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuarioResponse")]
        SimuladorCliente.ServiceReference1.RespuestaBase CambiarEstadoUsuario(string identificacion, string nuevoEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> CambiarEstadoUsuarioAsync(string identificacion, string nuevoEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionServiceChannel : SimuladorCliente.ServiceReference1.IAutenticacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionServiceClient : System.ServiceModel.ClientBase<SimuladorCliente.ServiceReference1.IAutenticacionService>, SimuladorCliente.ServiceReference1.IAutenticacionService {
        
        public AutenticacionServiceClient() {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SimuladorCliente.ServiceReference1.RespuestaBase AutenticarUsuario(string usuarioEncriptado, string contrasenaEncriptada, int tipoUsuario) {
            return base.Channel.AutenticarUsuario(usuarioEncriptado, contrasenaEncriptada, tipoUsuario);
        }
        
        public System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> AutenticarUsuarioAsync(string usuarioEncriptado, string contrasenaEncriptada, int tipoUsuario) {
            return base.Channel.AutenticarUsuarioAsync(usuarioEncriptado, contrasenaEncriptada, tipoUsuario);
        }
        
        public SimuladorCliente.ServiceReference1.RespuestaBase CrearUsuario(SimuladorCliente.ServiceReference1.UsuarioModelo nuevoUsuario) {
            return base.Channel.CrearUsuario(nuevoUsuario);
        }
        
        public System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> CrearUsuarioAsync(SimuladorCliente.ServiceReference1.UsuarioModelo nuevoUsuario) {
            return base.Channel.CrearUsuarioAsync(nuevoUsuario);
        }
        
        public SimuladorCliente.ServiceReference1.RespuestaBase ModificarUsuario(SimuladorCliente.ServiceReference1.UsuarioModelo usuarioModificado) {
            return base.Channel.ModificarUsuario(usuarioModificado);
        }
        
        public System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> ModificarUsuarioAsync(SimuladorCliente.ServiceReference1.UsuarioModelo usuarioModificado) {
            return base.Channel.ModificarUsuarioAsync(usuarioModificado);
        }
        
        public SimuladorCliente.ServiceReference1.RespuestaBase CambiarEstadoUsuario(string identificacion, string nuevoEstado) {
            return base.Channel.CambiarEstadoUsuario(identificacion, nuevoEstado);
        }
        
        public System.Threading.Tasks.Task<SimuladorCliente.ServiceReference1.RespuestaBase> CambiarEstadoUsuarioAsync(string identificacion, string nuevoEstado) {
            return base.Channel.CambiarEstadoUsuarioAsync(identificacion, nuevoEstado);
        }
    }
}
